- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: "Devopd with AWS"
    DURATION: "140HRS"
    TRAINER: "Sivakumar Reddy"
  tasks: 
    - name: print variables
      ansible.builtin.debug:
        msg: "courseis: {{ COURSE }}, Trainer is: {{ TRAINER }}" 